/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteImport } from './routes/_legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/_legal/terms-of-service'
import { Route as LegalSecurityRouteImport } from './routes/_legal/security'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/_legal/privacy-policy'
import { Route as LegalComplianceRouteImport } from './routes/_legal/compliance'

const LegalRoute = LegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LegalRoute,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalComplianceRoute = LegalComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof LegalComplianceRoute
  '/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/security': typeof LegalSecurityRoute
  '/terms-of-service': typeof LegalTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof LegalComplianceRoute
  '/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/security': typeof LegalSecurityRoute
  '/terms-of-service': typeof LegalTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_legal': typeof LegalRouteWithChildren
  '/_legal/compliance': typeof LegalComplianceRoute
  '/_legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/_legal/security': typeof LegalSecurityRoute
  '/_legal/terms-of-service': typeof LegalTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/_legal'
    | '/_legal/compliance'
    | '/_legal/privacy-policy'
    | '/_legal/security'
    | '/_legal/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal/terms-of-service': {
      id: '/_legal/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/security': {
      id: '/_legal/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/privacy-policy': {
      id: '/_legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/compliance': {
      id: '/_legal/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof LegalComplianceRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalComplianceRoute: typeof LegalComplianceRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalComplianceRoute: LegalComplianceRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
